---
# file: roles/ansible-role-minc_toolkit/tasks/main.yml

## update apt cache
#
# We keep this even if it is not used in order to test sudo

- name: "update apt cache"
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 3600
  tags: [ 'packages' ]

## install utilities

- name: "Utilities - ensure for `curl`"
  become: true
  apt:
    name: '{{ item }}'
    state: '{{ minc_state }}'
  with_items:
    - wget
  tags: [ 'packages', 'utilities' ]

## Gather minc-toolkit resources on remote system

- name: "Download latest stable version of minc toolkit (for ubuntu 12.04) from Github"
  get_url:
    url: '{{ minc_github_stable_package_url }}'
    dest: '{{ minc_local_resource_path }}'
  tags: [ 'packages', 'minc' ]


- name: "Install the lastest version of minc toolkit (for Ubuntu 12.04) available on Github"
  become: true
  apt:
    deb: '{{ minc_local_resource_path }}'
    state: present
  tags: [ 'packages', 'minc' ]

- name: create versioned minc
  become: true
  command: cp -r /opt/minc /opt/minc-'{{ minc_ver }}' chdir=/ creates=/opt/minc-'{{ minc_ver }}'/bin/mincinfo

# User configuration

## We ensure for the cretaion of the directory /etc/skel/bin
#
# done via dependancy in meta/main.yml

## Ensure for executable ~/bin/minc-toolkit-config.sh
#
# done via dependancy in meta/main.yml

## Ensure for versioned executable ~/bin/minc-toolkit-config.sh
#
# done via dependancy in meta/main.yml

 
